### ISSUE TITLE
issue with operators

### ISSUE THREAD

**Issue by Porizm** [viktorstrate/algebra-latex#14]
Hello,

I am struggling with plus and minus operators

"x + 1" is giving  tex "x+1"

But "x +- 1" is giving tex "x+-1"

and "x -- 1" is giving tex "x--1"

is there a way to remove the extra operator after using toLatex ?

Thank you in advance

**Comment by viktorstrate** [comment]
`x +- 1` will be parsed as `x + (-1)`, I guess the formatter could be improved by adding the explicit parenthesis
