### ISSUE TITLE
Ommiting the implied multiplication

### ISSUE THREAD

**Issue by Benjadahl** [viktorstrate/algebra-latex#2]
I would like to be able to avoid the implied multiplication of variables, so that it is possible to have variables with names longer than one character.

I attempted to add this behavior in my fork at commit 5f9f340 however, I believe the implementation is a tad bad, so I did not create a PR, do you know of a better way to do this?

I am also experiencing some weird behavior with it, where it will always follow the first parameter you gave it. Even if you call the function a second time.

Thanks for your time and great project :)

**Comment by viktorstrate** [comment]
I think it should be a part of the parser, instead of the formatter. I will work on a solution, thanks for the feedback.

**Comment by Benjadahl** [comment]
Thanks a lot!
