### ISSUE TITLE
new AlgebraLatex().parseLatex(string) throws error

### ISSUE THREAD

**Issue by pacopicon** [viktorstrate/algebra-latex#6]

**Comment by pacopicon** [comment]
This throws error => `let x = '9+8-7\\cdot 6\\left(5+4-3\\left(2\\right)\\left(6\\right)\\right)8-\\left(4\\right)2\\left(3\\right)'`, `new AlgebraLatex().parseLatex(x)`  

![image](https://user-images.githubusercontent.com/13924273/55422987-f3ef5500-554a-11e9-93f1-a6ebceba669c.png)

However, this string is parsed fine in Symbolab -> https://www.symbolab.com/solver/step-by-step/9%2B8-7%5Ccdot6%5Cleft(5%2B4-3%5Cleft(2%5Cright)%5Cleft(6%5Cright)%5Cright)8-%5Cleft(4%5Cright)2%5Cleft(3%5Cright)

**Comment by viktorstrate** [comment]
Thank you for reporting the problem. I have fixed the issue in 21983c3
